### ISSUE TITLE
xcproj fails to touch project.

### ISSUE THREAD

**Issue by swizzlr** [0xced/xcproj#3]
This issue is reproducible on my Mavericks server, but not on my ML machine with Xcode 5.

This occurred while using Cocoapods 0.24.0 under rvm stable running 2.0.0 p247.

I ensured there was no misconfiguration by running `sudo xcode-select --print-path`, and it is running Xcode 5. The sudoless variant returns the same path.

This isn't greatly affecting me but I'm willing to provide you with any necessary information to reproduce and fix the issue, or at least locate a workaround.

<pre><code>xcproj --project /Users/swizzlr/Documents/********/Pods/Pods.xcodeproj touch
The DevToolsCore framework failed to load: Error Domain=NSCocoaErrorDomain Code=3587 "The bundle “Xcode Core Framework” couldn’t be loaded because it is damaged or missing necessary resources." (dlopen_preflight(/Applications/Xcode5-DP6.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore): Library not loaded: @rpath/libclang.dylib
  Referenced from: /Applications/Xcode5-DP6.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore
  Reason: image not found) UserInfo=0x7fae9ae042b0 {NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode5-DP6.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore, NSDebugDescription=dlopen_preflight(/Applications/Xcode5-DP6.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore): Library not loaded: @rpath/libclang.dylib
  Referenced from: /Applications/Xcode5-DP6.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore
  Reason: image not found, NSBundlePath=/Applications/Xcode5-DP6.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework, NSLocalizedDescription=The bundle “Xcode Core Framework” couldn’t be loaded because it is damaged or missing necessary resources.}</code></pre>

**Comment by 0xced** [comment]
Can you please try to install [xcproj @ 8dbfe9c223](https://github.com/0xced/xcproj/archive/8dbfe9c223.zip) and see if the problem is fixed? I don’t have Mavericks so I can’t test if my tentative fix will actually work.

Do you have the `/usr/lib/libclang.dylib` file on Mavericks? If no, then this could explain why xcproj is working on Mountain Lion but not on Mavericks.

**Comment by 0xced** [comment]
Can you please test [xcproj @ fbf8c689c8](https://github.com/0xced/xcproj/archive/fbf8c689c8.zip) instead? It should output better error messages in case of failure.

**Comment by swizzlr** [comment]
Can confirm it works with the latest one. Want me to update the keg for home-brew?

**Comment by 0xced** [comment]
Have you tried with the Xcode 5 GM seed and the latest xcproj? The OS X 10.9 was removed from the Xcode 5 GM seed and it made xcproj fail. I have worked around it but nobody confirmed yet if it works properly.

Note that you **must** now compile xcproj like this, with the `-scheme xcproj` option:

```
xcodebuild -scheme xcproj install DSTROOT=/
```

I’d like at least one person to confirm it works well so that I can tag a new release.
